# Generated by Django 4.2.1 on 2023-06-01 05:45

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body_markdown', markdownfield.models.MarkdownField(rendered_field='body')),
                ('body', markdownfield.models.RenderedMarkdownField()),
            ],
        ),
    ]
