# Generated by Django 4.2.1 on 2023-06-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_body_markdown_note_created_at_note_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
